package waf

import (
	"bytes"
	"fmt"
	"regexp"
	"text/template"
	"time"

	"github.com/developmi/caddy-waf-ui/internal/domain"
)

// ExclusionType defines the exclusion types supported by our UI.
type ExclusionType string

const (
	ExcludeByID  ExclusionType = "id"
	ExcludeByTag ExclusionType = "tag"
)

// Exclusion represents a specific rule to disable in the Coraza CRS. Param,
// when not empty, scopes the exclusion to the query parameter ARGS:<param>
// (decision D5); if empty, the exclusion is at URI level (bare directive).
type Exclusion struct {
	Type  ExclusionType `json:"type"`
	Value string        `json:"value"`
	Param string        `json:"param,omitempty"`
}

// idBase is the base of the autogenerated ids for the SecRule directives
// that apply ctl:ruleRemoveById in a parameter-targeted way (D5: 9000001+).
const idBase = 9000001

const exclusionsTemplate = `# Caddy WAF UI managed - do not edit manually
{{ .Header }}

{{ range .Exclusions -}}
{{ if eq .Type "id" -}}
{{ if .Param -}}
SecRule ARGS:{{ .Param }} "@unconditionalMatch" "id:{{ .ID }},phase:2,pass,nolog,ctl:ruleRemoveById={{ .Value }}"
{{ else -}}
SecRuleRemoveById {{ .Value }}
{{ end -}}
{{ else if eq .Type "tag" -}}
{{ if .Param -}}
SecRule ARGS:{{ .Param }} "@unconditionalMatch" "id:{{ .ID }},phase:2,pass,nolog,ctl:ruleRemoveByTag={{ .Value }}"
{{ else -}}
SecRuleRemoveByTag "{{ .Value }}"
{{ end -}}
{{ end -}}
{{ else -}}
# No exclusions configured for this domain.
{{ end }}
`

// exclusionRow is the already validated and deduplicated entry ready to
// render: it carries the autogenerated id (0 = URI level, without its own
// SecRule).
type exclusionRow struct {
	Exclusion
	ID int
}

type exclusionsData struct {
	Header     string
	Exclusions []exclusionRow
}

// exclusionsTmpl is parsed ONCE at package level (finding J5-8), same pattern
// as ui/embed.go: the constant template never fails to parse.
var exclusionsTmpl = template.Must(template.New("exclusions").Parse(exclusionsTemplate))

// Strict patterns for the exclusion values: they reject any control
// character, quote, # or space that would allow injecting CRS directives.
var (
	exclusionIDRegex  = regexp.MustCompile(`^[0-9]+$`)
	exclusionTagRegex = regexp.MustCompile(`^[A-Za-z0-9_-]+$`)
	// The query parameter names stay equally strict because they travel
	// literally inside ARGS:<param> in the Caddyfile.
	exclusionParamRegex = regexp.MustCompile(`^[A-Za-z0-9_-]+$`)
)

// validateExclusions validates each entry before rendering to prevent CRS
// directive injection (e.g. "\nSecRuleEngine Off"). On any invalid entry it
// returns an explicit error (fail-loud).
func validateExclusions(exclusions []Exclusion) error {
	for _, ex := range exclusions {
		switch ex.Type {
		case ExcludeByID:
			if !exclusionIDRegex.MatchString(ex.Value) {
				return fmt.Errorf("invalid id exclusion %q: only digits are allowed", ex.Value)
			}
		case ExcludeByTag:
			if !exclusionTagRegex.MatchString(ex.Value) {
				return fmt.Errorf("invalid tag exclusion %q: only letters, numbers, hyphens and underscores are allowed", ex.Value)
			}
		default:
			return fmt.Errorf("unknown exclusion type %q: only %q or %q are allowed", ex.Type, ExcludeByID, ExcludeByTag)
		}
		if ex.Param != "" && !exclusionParamRegex.MatchString(ex.Param) {
			return fmt.Errorf("invalid exclusion parameter %q: only letters, numbers, hyphens and underscores are allowed", ex.Param)
		}
	}
	return nil
}

// ValidateExclusions exposes the validation to the shared service (D2) so
// the chain validates BEFORE taking the backup (validate → backup →
// generate...).
func ValidateExclusions(exclusions []Exclusion) error {
	return validateExclusions(exclusions)
}

// dedupeExclusions removes repeated entries (same type+value+param).
// The first occurrence wins; the rest are discarded ("duplicates
// deduplicated" scenario of the waf-exclusions spec).
func dedupeExclusions(exclusions []Exclusion) []Exclusion {
	seen := make(map[string]struct{}, len(exclusions))
	unique := make([]Exclusion, 0, len(exclusions))
	for _, ex := range exclusions {
		key := string(ex.Type) + "\x00" + ex.Value + "\x00" + ex.Param
		if _, ok := seen[key]; ok {
			continue
		}
		seen[key] = struct{}{}
		unique = append(unique, ex)
	}
	return unique
}

// GenerateExclusions creates the configuration block with the excluded CRS
// rules. It is a pure function, free of side effects.
func GenerateExclusions(site *domain.Site, exclusions []Exclusion) ([]byte, error) {
	if err := validateExclusions(exclusions); err != nil {
		return nil, err
	}

	// The parameter-targeted exclusions receive their own ids 9000001+ in
	// order of appearance (D5), only after discarding duplicates.
	rows := make([]exclusionRow, 0, len(exclusions))
	nextID := idBase
	for _, ex := range dedupeExclusions(exclusions) {
		row := exclusionRow{Exclusion: ex}
		if ex.Param != "" {
			row.ID = nextID
			nextID++
		}
		rows = append(rows, row)
	}

	// Header of 2 segments (without mode): shared contract domain.Header.
	data := exclusionsData{
		Header:     domain.Header(site.Domain, "", time.Now()),
		Exclusions: rows,
	}

	var buf bytes.Buffer
	if err := exclusionsTmpl.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("error executing exclusions template: %w", err)
	}

	return buf.Bytes(), nil
}
